config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :movies do
    collection do
      get 'search'
    end
      resources :reviews, except: [:show, :index]
  end
  root 'movies#index'

  get 'api/movies/all' => 'movies#fetch_movies'

end  

app/models/movie.rb
require 'elasticsearch/model'
class Movie < ActiveRecord::Base

	validates :title, presence: true, length: {minimum: 5}
	validates :description, presence: true 
	validates :director, presence: true 
	validates :duration, presence: true, numericality: true
	belongs_to :user
	has_many :reviews
	has_attached_file :image, :styles => {small: "150x150>", :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  searchkick word_start: [:title, :director]

  def image_url
  	image.url
  end

end
Movie.import # for auto sync model with elastic search

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :movies

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews
  
  attr_accessor :login, :image
	
	def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    if conditions[:username].nil?
	      where(conditions).first
	    else
	      where(username: conditions[:username]).first
	    end
	  end
	end

	validates :username,
	  :presence => true,
	  :uniqueness => {
	    :case_sensitive => false
	  } # etc.
    

    has_attached_file :image, :styles => {small: "150x150>", :medium => "300x300>", :thumb => "100x100>" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_filter :cors_preflight
  after_filter :cors_set_control_headers

  def cors_set_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
  end

  def cors_preflight
    if request.method == :options
      render json: { status: "ok"}, status: :ok
    end
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :image) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password, :image) }
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :destroy]

  def search
    if params[:search].present?
      @movies=Movie.search(params[:search])
    else
    @movies = Movie.all
    end
  end

  def index
      @movies = Movie.all
  end

  def show
    #@reviews = Review.where(movie_id: @movie.id).order("updated_at DESC")
    @reviews = @movie.reviews.order("updated_at DESC")
    if @reviews.nil?
      @average_rating = 0
    else
      @average_rating = @reviews.average(:rating)
    end
  end

  # GET /movies/new
  def new
      @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetch_movies
    render json: Movie.all.to_json( :methods => [:image_url] ), status: :ok
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :duration, :director, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie

  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = current_user.reviews.build(review_params)
    @review.movie_id = @movie.id    
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        #format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
    </div>

          <div><%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-left", role: "search" do %>
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Search' %>
          <% end %>

          
          </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if user_signed_in? %>
                  <ul class="nav navbar-nav navbar-right">
                      <li><%= link_to "Welcome back, " + current_user.username + "!", edit_user_registration_path %></li>
                      <%#= image_tag current_user.image.url(:thumb) %>
                      <li><%= link_to "Account", edit_user_registration_path %></li>
                      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                  </ul>
              <% else %>
                  <ul class="nav navbar-nav navbar-right">
                      <li><%= link_to "Sign up", new_user_registration_path %></li>
                      <li><%= link_to "Sign in", new_user_session_path %></li>
                  </ul>
              <% end %>
              
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info")%>
    <% end %>
    <%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie, html: { multipart: true}) do |f| %>

  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% if current_user %>
<% end %>

<% @movies.each do |movie| %>

  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
    <%= image_tag movie.image.url(:medium) %>
      <div class="caption">
        <h3><center><%= movie.title %></center></h3>
        
        <%#= movie.duration %>
        <%#= movie.director %>



        <% if current_user %>
        <p><center><button><%= link_to 'Show', movie %></button>       
        <button><%= link_to 'Edit', edit_movie_path(movie) %></button>
        <button><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></button></center></p>
        <% else %>
        <p><center><button><%= link_to 'Show', movie %></button></center></p>
      <% end %> 

      </div>
    </div>
  </div>
    <% end %> 
<br>

<% if current_user %>

  <footer>
  <div class="container">
  <%= link_to 'New Movie', new_movie_path %>
  </div>
</footer>

<% end %>  

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
      </div>
      <div id=" buttons">
          <center>
            <%= link_to 'Show', movie %>
            <% if current_user %>
            <%= link_to 'Edit', edit_movie_path(movie) %>
            <%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?'} %>
            <% end %>
          </center>
      </div>  
      <br>      
    </div>
  <% end %>
</div>

app/views/movies/show.html.erb
<div class="container">

            <div class="row row-margin-bottom">
            <div class="col-md- no-padding lib-item" data-category="view">
                <div class="lib-panel">
                    <div class="row box-shadow">
                        <div class="col-md-4">
                        <div class="thumbnail">
<%= image_tag @movie.image.url(:medium) %>
</div>
                        </div>
                        <div class="col-md-6">
                            <div class="lib-row lib-header">
  								<%= @movie.title %>
                                <div class="lib-header-seperator"></div>
                            </div>
                            <div class="lib-row lib-desc">

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @movie.duration %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
<strong>Average Rating is:</strong>  
</p>

<style type="text/css">
    #rating img{
        width: auto!important;
    }
</style>
<div id="rating" class="col-md-12">
	<div class = "star-rating" data-number = <%= @average_rating %> ></div>
</div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>

<div class="container">
    <div class="row">
        <div class="panel panel-default widget">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-comment"></span>
	<strong>Comments:</strong>
	<%= pluralize(@movie.reviews.count, "comment") %>

            </div>
            <div class="panel-body">
                <ul class="list-group">
<% if current_user %>
                <%= render partial: 'reviews/new' %>
<% end %>
                	<% @reviews.each do |review| %>
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-xs-2 col-md-1">
                                <%= image_tag review.user.image.url(:thumb), :class => "img-circle img-responsive" %>
                                </div>
                            <div class="col-xs-10 col-md-11">
                                <div>
                                    <div class="mic-info">
                                        By: <%= review.user.username %> <em> (<%= time_ago_in_words(review.updated_at) %> ago)</em>	
                                    </div>
                                </div>
                                	<div class = "star-rating" data-number = <%= review.rating %> ></div> 
                                <div class="comment-text">
                                    <%= review.comment %> 
                                </div>
                                <div class="action">

	<% if current_user %>
		<% if current_user.id == review.user.id %>
			<%= link_to "Edit Review", edit_movie_review_path(@movie, review) %><br>
		<% end %>
	<% end %>

                                
                            </div>
                        </div>
                    </li>
	<% end %>
                </ul>
            </div>
        </div>
    </div>
</div>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

<script>
	$('.star-rating').raty({
		path: '/assets/',
		readOnly: true, 
		score: function () {
			return $(this).attr('data-number');
		}
	})
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @movie.reviews.new]) do |f| %>


<div>
  <div id="star-rating"></div>
</div>



 
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
 $('#star-rating').raty( {

  path: '/assets/',
  scoreName: 'review[rating]'
 })

</script>

app/views/reviews/_new.html.erb
<h4><em>Add a review!</em></h4>

<%= render 'reviews/form' %>

<%#= link_to 'Back', movie_path(@movie) %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>



<%= form_for([@movie, @review], :html => { :multipart => true }) do |f| %>


  <div class="field">
    <div class="star-rating"></div>
  </div>
  
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>



<script>
 $('.star-rating').raty( {

  path: '/assets/',
  scoreName: 'review[rating]'
 })

</script>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>